### ISSUE TITLE
forgot array()?

### ISSUE THREAD

**Issue by kmvan** [bencagri/Simple-TxtDb#1]
Thanks your codes.
`$db = new TxtDb('name' => 'TABLE-NAME',
  'path'      => 'db/',
  'extension' => '.txtdb',
  'encrypt'   => FALSE);`
maybe is
`$db = new TxtDb(array('name' => 'TABLE-NAME',
  'path'      => 'db/',
  'extension' => '.txtdb',
  'encrypt'   => FALSE));` 
?

**Comment by bencagri** [comment]
Yes. Thank you kmvan. I'm fixing it.
